---
- name: set timezone
  shell: ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

- name: update system
  shell: yum clean all && yum makecache && yum update-minimal -y

- name: erase firewalled
  shell: yum erase -y firewalld

# install git
- include: git.yml

# install zsh
- include: zsh.yml