FROM larrycai/gerrit
MAINTAINER zyfdegg@gmail.com

ENV GERRIT_USER gerrit2
ENV GERRIT_HOME /home/${GERRIT_USER}

USER root
WORKDIR /

RUN apt-get -y update && \
    apt-get -y install python-setuptools vim && \
    apt-get -y install mysql-client && \
    easy_install supervisor && \
    mkdir -p /opt/itri && \
    ln -f -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN apt-get -y install libmysql-java

ADD supervisord.conf /etc/supervisord.conf
ADD start.sh /start.sh
ADD stop.sh /stop.sh
ADD config.sh /config.sh
ADD restart.sh /restart.sh
ADD init.sh /init.sh
ADD init.sql  /init.sql
ADD create_gerrit_user.sql  /create_gerrit_user.sql
RUN chmod +x /*.sh

ADD gerrit.config $GERRIT_HOME/gerrit/etc/gerrit.config

RUN rm -rf $GERRIT_HOME/gerrit/git/*

RUN cp /usr/share/java/*.jar $GERRIT_HOME/gerrit/lib/

RUN cp $GERRIT_HOME/gerrit/lib/mysql-connector-java.jar $GERRIT_HOME/gerrit/lib/mysql-connector-java-5.1.21.jar

ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64/jre

VOLUME ["/home/gerrit2/gerrit/git"]

CMD ["/usr/local/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]






 
