---
- name: common task
  hosts: allmachines

  roles: 
  - { role: common }

- name: install zookeeper
  hosts: zookeeper

  roles:
  - { role: zookeeper }

- name: install mesos
  hosts: allmachines

  roles:
  - { role: mesos }

- name: install marathon
  hosts: marathon
  
  roles:
  - { role: java }
  - { role: marathon }

- name: install docker
  hosts: mesos_slave

  roles:
  - { role: docker }

